name: Integration CI

run-name: "${{ contains(github.head_ref, 'feature/') && 'Feature' || contains(github.head_ref, 'bugfix/') && 'Bugfix' || 'Update' }}: ${{ github.head_ref }} by @${{ github.actor }}"

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        python-version: ["pypy3.9", "pypy3.10", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install --prefix ./SereniChat/src/frontend
      - run: npm run build --prefix ./SereniChat/src/frontend

      - name: Python Setup ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.9+'
          cache: 'pip'
      - run: |
          if [ ! -d ./SereniChat/src/backend/venv ]; then
            python3 -m venv ./SereniChat/src/backend/venv
          fi
          source ./SereniChat/src/backend/venv/bin/activate
          pip install -r ./SereniChat/src/backend/requirements.txt
          pip freeze > ./SereniChat/src/backend/requirements.txt
