name: Post-Merge Workflow

on:
  push:
    branches-ignore:
      - main
      - master
  pull_request:
    types: [closed]
    branches-ignore:
      - main
      - master

jobs:
  delete-branches:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Post-Merge Steps
          run: |
            echo "Performing post-merge steps..."

        - name: Pull Changes
          run: git pull origin ${GITHUB_REF#refs/heads/}

        - name: Push Changes
          run: git push origin ${GITHUB_REF#refs/heads/}

        - name: Delete Merged Branch
          if: steps.check-pr.outputs.is_pull_request == 'true'
          run: |
            git branch -d ${{ github.event.pull_request.head.ref }}
            git push origin --delete ${{ github.event.pull_request.head.ref }}